#!/usr/bin/env perl
# (c) 2016 - 2019 CHAO
# ===================================================================
my $Description  =  "Metagenome Beads Barcode Quantifictaion launcher";
# Author:            Chao | fangchao@genomics.cn
my $version      =  0.1;
# Last modified:    13 Jan 2019 (since 13 Jan 2019)
# ===================================================================
# see detail below
use warnings;
use strict;
use Getopt::Long;
use File::Basename;
use FindBin qw($RealBin);
use Cwd 'abs_path';
use Getopt::Long qw(:config no_ignore_case); # For case sensitive

my $cwd = abs_path;
my $Bin = $RealBin;
my $cmd = basename $0;
my $msg = $Description;

sub usage {
  my $msg = shift;
print <<USAGE;
$msg
usage:
  $cmd <bb|cfg|cmd> [option]
mode:
    bb   Initiate bead-barcode pipeline
    cfg  Generata a default config file under current dir
    cmd  List sub functions in src/util directory
    ***  Call sub functions from the list cmd shows you.
         e.g: "$cmd OAs1" will run OAs1 without its absolute path.
options  Defined according to the mode and cmd you chosed.
USAGE
}

sub usageBB {
  my $msg = shift;
print <<USAGE;
$msg
usage:
  $cmd bb [option]
options:
    -i  input dataset list file
    -o  output dir
    -c  config file
    -v  version
    -V  verbose
    -h  show help info
USAGE
}

&usage($msg) && exit if @ARGV == 0 || $ARGV[0] eq "-h";
die "version $version\n" if $ARGV[0] eq "-v";

#################################
####  config calling module  ####
my $pattern = $ARGV[0];
if($pattern eq "cfg"){
    `cp $RealBin/default.cfg $cwd/`;
    exit;
}

#################################
###  sub func calling module  ###
if ($pattern eq "cmd"){
	print "Available sub commands:\n";
	system("ls --color $Bin/src");
	print "Available util commands:\n";
	system("ls --color $Bin/util");
	exit;
}
if ($pattern !~ /^(bb|cfg|-v|-h)$/){
  my $path = ( -e "$Bin/src/$pattern")?"$Bin/src":
             ( -e "$Bin/util/$pattern")?"$Bin/util":'';
  die "[cmd] Can not find sub func '$pattern'. Please check it again.\n" unless $path;
  my $int = ($pattern=~/\.pl$/)?'perl ':
            ($pattern=~/\.py$/)?'python ':
            ($pattern=~/\.sh$/)?'sh ':
            ($pattern=~/\.[Rr]$/)?'Rscript ':'';
    print STDERR "$int$path/@ARGV\n";
	if(system("$int$path/@ARGV")){
		exit(1);
	}else{
		exit;
	}
}

&verbose("[log] BB mode Start");
#################################
##########  MAIN BODY  ##########
our(%CFG,%SAM);
my ($inf,$out,$cfg,$verbose,$help);
GetOptions(
  "i=s" => \$inf,
  "o=s" => \$out,
  "c=s" => \$cfg,
  "V" => \$verbose,
  "v" => \$version,
  "h|help|?" => \$help,
);
&usageBB("Initiate bead-barcode pipeline") && exit if $help;
&usageBB("[fatal] Essential input is missing") && exit unless defined $inf;
$out ||= ".";

&verbose("[bb] Init workshop\n");
my($dirDB, $dirIN);
$out = abs_path($out);
system "mkdir -p $out" unless(-d $out);
$dirDB = "$out/database";
$dirIN = "$out/rawSeq";
system "mkdir -p $dirDB" unless(-d $dirDB);
system "mkdir -p $dirIN" unless(-d $dirIN);

&verbose("[bb] Prep config.yaml\n");
open SCFG, ">$out/config.yaml" or die "can not write config.yaml. Please check\n";

&verbose("[bb] Read config\n");
&readCFG($cfg);
&writeCFG;
&verbose("[bb] Read input list\n");
&readInput($inf);

&verbose("[bb] Link required files\n");
die "barcodes list not defined. Check again.\n" unless $CFG{'BeadBarcodeList'};
$CFG{'BeadBarcodeList'} = abs_path($CFG{'BeadBarcodeList'});
system "ln -sf $CFG{'BeadBarcodeList'} $dirDB/barcode.list";

print SCFG "samples:\n";
foreach my $sam (sort keys %SAM){
  my @fs = @{$SAM{$sam}};
  for(my $i=1;$i<=@fs;$i++){
    $fs[$i-1] =~ /.(f(|ast)[aq](|.gz))$/;
    my $sufix = $1;
    system "ln -sf $fs[$i-1] $dirIN/$sam\_$i.$sufix";
    print SCFG "  $sam: rawSeq/$sam\n";
  }
}
close SCFG;
system "cp $Bin/Snakefile $out/Snakefile";
&verbose("done!\n");

exit;
#################################
##########  Sub funcs  ##########
sub verbose{
  my $msg = shift;
  print STDERR $msg if $verbose;
}

sub readCFG {
  my $cfg = shift;
  if($cfg =~ /\.cfg$/ && -e $cfg ){
    open CFG,"$cfg" or die "failed to open configure file $cfg. $!\n";
    while(<CFG>){
      chomp;
      next if $_ =~ /^#/ || $_ eq "";
      $_ =~ /(\S+)\s*=\s*(\S+)/;
      $CFG{$1} = $2;
    }
  }else{
    foreach my $par (split(/,/,$cfg)){
      my @a = split(/=/,$par);
      $CFG{$a[0]} = $a[1];
    }
  }
}

sub readInput {
  my $path_f = shift;
  my @paths = split (',',$path_f);
  open PATH,"> $out/sam.id.path" or die $!;
  while(@paths>0){
  	my $path_i = shift @paths;
  	$path_i = abs_path($path_i);
  	open IN,"<$path_i" or die "can not open $path_i, $!\n";
  	while (<IN>){
  		print PATH $_ ;
  		chomp;
  		my @a = split;
          $a[1] = abs_path($a[1]);
  		my ($sam,$path) = @a;
  		push @{$SAM{$sam}}, $path;
  	}
  	close IN;
  }
  close PATH;
}

sub writeCFG {
  print SCFG "BeadBarcodeList: ".(($CFG{'BeadBarcodeList'})?"\"$CFG{'BeadBarcodeList'}\"\n\n":"\"unknown\"\n\n");
  print SCFG "prefix: ".(($CFG{'prefix'})?"\"$CFG{'prefix'}\"\n\n":"\"default\"\n\n");
  print SCFG "tmp: ".(($CFG{'tmp'})?"\"$CFG{'tmp'}\"\n\n":"\"./tmp\"\n\n");
  print SCFG "threads: ".(($CFG{'threads'})?$CFG{'threads'}:1)."\n\n";
  print SCFG "max_threads_per_script:  ".(($CFG{'max_threads_per_script'})?$CFG{'max_threads_per_script'}:1)."\n\n";
  print SCFG "divideSH:  ".(($CFG{'divideSH'})?$CFG{'divideSH'}:10)."\n\n";
}
