#!/usr/bin/env perl
# Restore the barcode list of each node computed by Community detection.
#-----------------------------------------------------------------------------
# Author : Chao Fang
# Email  : fangchao@genomics.cn
# Create : Nov 2018
#-----------------------------------------------------------------------------
# see usage below
use strict;
use Getopt::Long;

sub usage {
  my $msg = shift;
print <<USAGE;
$msg
usage:
  $0 -n node -m map -o output
    -n  node file generated by hierarchy com
    -m  map list connect the node id to barcode
    -v  verbose mode
    -h  show help info
USAGE
}

my ($node,$map,$out,$verbose,$help);
GetOptions(
  "n=s" => \$node,
  "m=s" => \$map,
  "o=s" => \$out,
  "v" => \$verbose,
  "h|help|?" => \$help,
);
&usage && exit if $help;
&usage("[fatal] Essential argments missing") && exit unless $map && $node;

open MAP, "< $map" or die $!;
open NOD," < $node" or die $!;
open OUT, ($out)?"|sort -n >$out":"|sort -n >STDOUT" or die $!;

my %MAP;
&verbose("[log] Reading <map> ...");
while(<MAP>){
  chomp;
  my @L = split(/\s|\t/,$_);
  $MAP{$L[0]} = $L[1];
}
close MAP;
&verbose("done\n");
&verbose("[log] Reading <node> & wirtting ...");
while(<NOD>){
  chomp;
  my @L = split(/\s|\t/,$_);
  print OUT "$L[1]\t$MAP{$L[0]}\n";
}
close NOD;
close OUT;
&verbose("done\n");
exit;

sub verbose{
  return 0 unless $verbose;
  my $msg = shift;
  print STDERR $msg;
}
